sudo: required
language: java
jdk: openjdk8

services:
  - docker

script:
  - ./gradlew clean build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t vivanou/multi-service ./service
  - docker build -t vivanou/multi-nginx ./nginx
  - docker push vivanou/multi-service
  - docker push vivanou/multi-nginx

deploy: 
  provider: elasticbeanstalk
  region: eu-central-1
  app: test
  env: Test-env
  bucket_name: elasticbeanstalk-eu-central-1-573032386643
  bucket_path: test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY