sudo: required
language: java
jdk: openjdk8

services:
  - docker

script:
  - ./gradlew clean build

after_success:
  - docker build -t vivanou/multi-service ./service
  - docker build -t vivanou/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vivanou/multi-service
  - docker push vivanou/multi-nginx