version: "3.7"
services:
  app:
    build: ./service
    ports:
    - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_TABLE=people
      - CACHE_HOST=cache
      - CACHE_PORT=6379
    depends_on:
      - cache
      - db
  cache:
    image: redis:latest
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=people
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    
      